#!/bin/sh

PNAME=JavaGD
SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/${PNAME}
echo "Copying package base ..."
cp -r ../${PNAME} /tmp

rm -f /tmp/${PNAME}/mkdist

cd /tmp/${PNAME}

if [ -e /tmp/${PNAME}/configure ]; then
    echo "Note: autoreconf is *not* ran automatically if configure exists."
    echo "      Run it manually if necessary."
else
    echo "Running autoreconf ..."
    autoreconf
    rm -rf autom4te*
fi

if [ ! -e getsp.class ]; then
    echo "Compiling getsp.class"
    javac -target 1.1 -source 1.2 getsp.java
fi

echo "Removing CVS and backup stuff ..."
find . -name CVS | xargs rm -rf
find . -name \*~ | xargs rm -f

if [ ! -e src/java/javaGD.jar ]; then
    make -C src/java 'JFLAGS=-source 1.2 -target 1.2'
    if [ $? != 0 ]; then
	exit 1
    fi
    mkdir -p inst/java
    mv src/java/javaGD.jar inst/java
    make -C src/java clean
fi

echo "Updating version ..."
VER=`awk -v ORS= '/JavaGD v/ { print substr($6,2) }' src/javaGD.h`
echo "JavaGD version ${VER}"
cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
mv d DESCRIPTION
echo "Creating package ..."
cd ..
tar fcz ${PNAME}_${VER}.tar.gz ${PNAME}
cd ${SWD}
cp /tmp/${PNAME}_${VER}.tar.gz ..
rm -rf /tmp/${PNAME}
echo "Done."
ls -l ../${PNAME}_${VER}.tar.gz
